### PR TITLE
Type checker visitor tests

### PR DESCRIPTION
**Pull request by BaBrixx**
Created tests for the type checker. Additionally huge parts of the type checker has been fixed and rewritten (Minor fixes ;-) ).

### CODE REVIEW

**Comment by NybyDK** [comment]
image

**Review by TSKsmiley — APPROVED** [review]
:)

**Review by AlbertHald — APPROVED** [review]
gugugaga

**Comment by TSKsmiley** [comment]
ezgif com-gif-maker(1)

**Pull request merged**
